server:
  port: 8082

spring:
  application:
    name: ResourceServer
    group: com.movie-netscape
    version: 1.0.0

  cloud:
    gateway:
      routes:

        # Protected routes for app-management-service
        - id: app-management-service
          uri: http://localhost:8088
          predicates:
            - Path=/api/v1/app-management/**

        # Protected routes for account-service
        - id: account-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/accounts/**


        # Protected routes for user-service
        - id: user-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/users/**


        # Protected routes for auth-service
        - id: auth-protected-routes
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**





  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    reactor.netty: DEBUG



    org:
      springframework:
        security=DEBUG: